### ISSUE TITLE
User can search the pets that are in an area

### ISSUE THREAD

**Issue by dulceherrera** [dulceherrera/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search the pets that are in an area.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to search for pets that are in an area by entering the location and the type of pet they want.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="981" alt="Screen Shot 2022-09-21 at 12 53 17 PM" src="https://user-images.githubusercontent.com/97363006/191598312-fa4c6b67-f1d8-4625-9638-2a4da63ff006.png">
<img width="987" alt="Screen Shot 2022-09-21 at 12 53 37 PM" src="https://user-images.githubusercontent.com/97363006/191598323-8d6cc649-9bce-4cb3-9dda-06e6e72f53c2.png">
<img width="1024" alt="Screen Shot 2022-09-21 at 12 56 19 PM" src="https://user-images.githubusercontent.com/97363006/191598738-2f1451ea-6be8-4cc7-81d1-64a3ff517e61.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Install the PetFinder npm package
- [x] Within index.js:
- [x] Call the require function on '@petfinder/petfinder-js'
- [x] Call the client method for apiKey and secret object
- [x] Use the PetFinder npm package to query the API
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to home page:
- [x] Create a navbar component 
- [x] Create a form component that contains a search input and a dropdown input
- [x] Create a page to show the pets that are in the area that the user selected
- [x] Use the property hash to add an identifier to the home page and the results page
- [x] The navigation bar icon should return the user to the home page 

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
