### ISSUE TITLE
User can sign out

### ISSUE THREAD

**Issue by dulceherrera** [dulceherrera/final-project#10]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sign out. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users who are logged in will be able to log out using the sign out tab.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="465" alt="Screen Shot 2022-09-14 at 1 35 12 PM" src="https://user-images.githubusercontent.com/97363006/190257748-f2e3e99d-21a4-42ce-9885-5f4caeccc12d.png">
<img width="193" alt="Screen Shot 2022-09-14 at 1 33 13 PM" src="https://user-images.githubusercontent.com/97363006/190257758-4fbded17-70f6-43dd-9363-e7c91bb87b81.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Create a component to sign out

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
