### ISSUE TITLE
User can save the pets that they liked

### ISSUE THREAD

**Issue by dulceherrera** [dulceherrera/final-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can save the pet that has interested them.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to save a pet that he liked by clicking on a heart-shaped icon

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="477" alt="Screen Shot 2022-09-22 at 3 56 02 PM" src="https://user-images.githubusercontent.com/97363006/191865923-e36000c8-124b-43dd-85a0-627edbe2efe3.png">
<img width="822" alt="Screen Shot 2022-09-22 at 3 56 56 PM" src="https://user-images.githubusercontent.com/97363006/191865932-72b0342f-7339-4ac8-b35a-7a856d7a368c.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Verify that database pets was created by running pgweb --db=pets
- [x] Verify the pet saved is in favorites table

### ☁️ Server Tasks

- [x] Update `server/index.js` to respond user's request
- [x] Insert the pet saved into the favorites table with PostgreSQL 
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a button to save pets in matches page.
- [x] Listen for OnClick event on the button created.
- [x] Ensure that petId is saved in the favorites table when the user saves the pet.
- [x] After save a pet, the page should shows a new pet.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
