### ISSUE TITLE
User can delete a match they are no interested in 

### ISSUE THREAD

**Issue by dulceherrera** [dulceherrera/final-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can delete a match that has not interested them

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

By pressing the circle button with an x in the center, the user will be able to eliminate matches that do not interest them.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="1017" alt="Screen Shot 2022-09-22 at 4 46 48 PM" src="https://user-images.githubusercontent.com/97363006/191872286-dbcab2a6-648a-4884-9841-f79bfcc7564a.png">
<img width="476" alt="Screen Shot 2022-09-22 at 5 15 10 PM" src="https://user-images.githubusercontent.com/97363006/191872296-b5295cb1-2d93-444a-9c67-4ae1509a8de0.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Add a button that removes the pet that the user is not interested in.
- [x] Listen for the onClick event on the button.
- [x] The page should shows a new pet after the button "x" is clicked. 

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
