### ISSUE TITLE
User can view the match list

### ISSUE THREAD

**Issue by dulceherrera** [dulceherrera/final-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to see the list of pets they liked

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to see all of the matches in the your pets tab.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="980" alt="Screen Shot 2022-09-22 at 6 06 57 PM" src="https://user-images.githubusercontent.com/97363006/191875966-e3881a13-6e4e-429a-8cfa-67e2ce471db2.png">
<img width="491" alt="Screen Shot 2022-09-22 at 6 07 17 PM" src="https://user-images.githubusercontent.com/97363006/191875969-3509c8af-de11-4e2c-8ac8-c7802d297402.png">
<img width="858" alt="Screen Shot 2022-09-22 at 6 07 45 PM" src="https://user-images.githubusercontent.com/97363006/191875970-ad3071c0-5db9-48bd-9fc8-df0c1af8da7d.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to get the pets saved in the database.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Add a drawer component to the navbar.
- [x] Add a home tab to the drawer component to return to the home page.
- [x] To show the pets saved, add a tab named Your Pets.
- [x] Create a Your Pets page to show the user's pets saved.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
