### ISSUE TITLE
User can view all the details of a pet

### ISSUE THREAD

**Issue by dulceherrera** [dulceherrera/final-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view the details of their pets saved. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can view more details of a pet by clicking it on the your pets page. There's will be a button to return to the your pets page. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="580" alt="Screen Shot 2022-09-25 at 1 01 46 PM" src="https://user-images.githubusercontent.com/97363006/192162951-812b483c-1de0-4bf9-b6e3-6448eebaa58b.png">
<img width="975" alt="Screen Shot 2022-09-25 at 12 59 42 PM" src="https://user-images.githubusercontent.com/97363006/192162954-0f953381-bd7c-43fe-9a7c-a35aed4821b6.png">
<img width="481" alt="Screen Shot 2022-09-25 at 12 59 58 PM" src="https://user-images.githubusercontent.com/97363006/192162955-5c45921a-873c-4567-99c2-d1f49ecb407b.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to get the details of the selected pet.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a pet details page to view the details of the pet.
- [x] Include a hash route for details page to app.jsx
- [x] Add a button to return to the pets saved.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
