### ISSUE TITLE
User can delete pets that they are no longer  interested in

### ISSUE THREAD

**Issue by dulceherrera** [dulceherrera/final-project#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can delete a pet that they are no longer interested in. 
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to delete a pet from their matches by clicking the heart in the photo. 
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="984" alt="Screen Shot 2022-09-25 at 4 22 33 PM" src="https://user-images.githubusercontent.com/97363006/192884288-9c38e516-cdf4-4d9b-b31c-adaea93c44f3.png">
<img width="581" alt="Screen Shot 2022-09-25 at 4 27 25 PM" src="https://user-images.githubusercontent.com/97363006/192884292-4a3f09ab-3e45-4cd6-8e84-995e083e7f83.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Make sure the pet was properly removed from the database.

### ☁️ Server Tasks

- [x] Update `server/index.js` to include a delete request.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Add a heart button to each pet saved.
- [x] Add a handleDelete method in the saved page.
- [x] Within the handleDelete method, loop through animals.length and check if this.state.animals[i].petId is equal to the selectedPet.
- [x] Ensure that saved.jsx reflects the changes after pet is deleted.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
