### ISSUE TITLE
User can view the location of each pet 

### ISSUE THREAD

**Issue by dulceherrera** [dulceherrera/final-project#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view the location of each pet. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to see on a google map the location of the pet on the details page. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="945" alt="Screen Shot 2022-09-14 at 1 22 01 PM" src="https://user-images.githubusercontent.com/97363006/190254830-a7033810-b997-4cc9-aacf-99a9be3f57e4.png">
<img width="408" alt="Screen Shot 2022-09-14 at 1 22 20 PM" src="https://user-images.githubusercontent.com/97363006/190254836-6b8687ce-f980-44ec-92ac-17a24d2bac12.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Install the react google maps package.
- [x] Install the google geocoding package.
- [x] Create a component for display google maps.
- [x] Make sure that the latitude and longitude are correct on the map.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
