### ISSUE TITLE
User can sign up for an account

### ISSUE THREAD

**Issue by dulceherrera** [dulceherrera/final-project#8]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sign up for an account.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to create an account on the page. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="466" alt="Screen Shot 2022-10-17 at 2 58 20 PM" src="https://user-images.githubusercontent.com/97363006/196291866-23724140-03e3-431e-b523-f40fe9887eb0.png">
<img width="868" alt="Screen Shot 2022-10-17 at 2 58 49 PM" src="https://user-images.githubusercontent.com/97363006/196291869-999f8aed-3d99-4781-92fb-bca7e8526fed.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to create a new table for users.
- [x] Update `data.sql` to insert data into user's table.

### ☁️ Server Tasks

- [x] Update `server/index.js` to respond a request for sign up.
- [x] Make sure the credentials are inserted into database
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component for sign up page.
- [x] Update hash routing for the sign up component.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
