### ISSUE TITLE
User can sign in

### ISSUE THREAD

**Issue by dulceherrera** [dulceherrera/final-project#9]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sign in on the app.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to sign in on the page using the information with which they signed up.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="947" alt="Screen Shot 2022-09-14 at 1 29 45 PM" src="https://user-images.githubusercontent.com/97363006/190256599-b94d4a27-45ec-4bd9-bf46-d5d21d91a637.png">
<img width="425" alt="Screen Shot 2022-09-14 at 1 30 01 PM" src="https://user-images.githubusercontent.com/97363006/190256601-b9ce5a7d-4348-48ac-bd72-0a2974d42784.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to respond to post request
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update navbar component to add sign in element
- [x] Add app-context.js in lib folder
- [x] Add decode-token.js in lib folder

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
